image: mono:latest

stages:
  - build

#before_script:
  #- nuget restore -NonInteractive

build:
  variables:
    GIT_STRATEGY: fetch
  stage: build
  only:
    - master
  artifacts:
    paths:
      - ./bin
  script:
    - make

      

